In [54]:
import os 
import sys
sys.path.insert(0, os.path.abspath('..'))

import yfinance as yf
import numpy as np
import pandas as pd

from algorithms import linear_regression, polynomial_regression, exponential_regression
from visualization import gen_polyplot, gen_exponential_plot

### Users guide

### For our regression model we chosee MOEX

###### Example data

In [75]:
df = yf.download('SI=F',start='2020-03-05', end='2022-01-01', interval='1mo')
df = df.dropna()
df.head()

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close  Adj Close  Volume
Date                                                                     
2020-04-01  14.080000  16.072001  13.900000  14.898000  14.898000   35732
2020-05-01  15.005000  18.440001  14.695000  18.440001  18.440001    2775
2020-06-01  18.785000  18.815001  17.379000  18.541000  18.541000   52341
2020-07-01  18.485001  26.020000  17.945000  24.188999  24.188999    5095
2020-08-01  24.389999  29.530001  24.389999  28.437000  28.437000  141618

###### forming arrays

In [76]:
X = np.arange(len(df))
Y = df['Close']
X = pd.Series(X, name='Time')

#### Linear regression with non-type regularization 

In [77]:
w_opt_none = linear_regression(X.values.reshape(-1,1), Y.values, flag_constant = True)
w_opt_none

array([21.62453714,  0.24817432])

#### Linear regression with L1 regularization (also you can make L2 wth  reg_type param)

In [79]:
w_opt_l1 = linear_regression(X.values.reshape(-1,1), Y.values, reg_type='l1', flag_constant = True, const_l1=0.9)
w_opt_l1

array([20.09453449,  0.36817463])

#### Polynomial regression with non-type regularization 

In [80]:
w_opt_none = polynomial_regression(X.values.reshape(-1,1), Y.values, degree=3)
w_opt_none

array([ 1.52736638e+01,  3.17851807e+00, -2.73288646e-01,  6.70098683e-03])

#### Polynomial regression with L1 regularization (also you can make L2 wth  reg_type param)

In [81]:
w_opt_l1 = polynomial_regression(X.values.reshape(-1,1), Y.values, reg_type='l1', degree=3)
w_opt_l1

array([ 1.49684671e+01,  3.24834844e+00, -2.77835772e-01,  6.78640223e-03])

#### Exponential regression with non-type regularization 

In [82]:
w_opt_none_exp = exponential_regression(X.values.reshape(-1,1), Y.values)
w_opt_none_exp

array([3.04648524, 0.01268507])

#### Exponential regression with L1 regularization (also you can make L2 wth  reg_type param)

In [83]:
w_opt_l1 = exponential_regression(X.values.reshape(-1,1), Y.values, reg_type='l1')
w_opt_l1

array([2.87648535, 0.0260184 ])

#### Plots of initial distribution and regression 

###### Use this function for linear and polynomial regression

In [84]:
gen_polyplot(X, Y, w_opt_none)

###### Use this function for exponential regression

In [85]:
gen_exponential_plot(X, Y, w_opt_none_exp)